ironman/urls.py
from django.urls import include, path

from . import views

app_name = 'ironman'
urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path('race/<int:race_id>/', views.RaceView.as_view(), name='race'),
    path('stats/', views.StatsView.as_view(), name='stats'),
]

triathloninfo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ironman.urls')),
]

ironman/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from model_utils import Choices
from datetime import datetime, timedelta
from .constants import WEBDRIVER_VERSION
from django.core.validators import MaxValueValidator, MinValueValidator

class Race(models.Model):
    DISTANCES = Choices(('half-ironman', _('IRONMAN 70.3')),
                        ('full-ironman', _('IRONMAN')))
    distance = models.CharField(choices=DISTANCES, max_length=40)
    title = models.CharField(max_length=255)
    date = models.DateField()
    location = models.CharField(max_length=255)
    version = models.SmallIntegerField(
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(WEBDRIVER_VERSION)])

    def get_computed_race_data(self):
        age_group_list = [age[0] for age in RaceResult.AGE_GROUPS]
        gender_list = [gender[0] for gender in RaceResult.SEXES]
        select_query = {
            'avg_swim': 'AVG(swim_time)',
            'avg_bike': 'AVG(bike_time)',
            'avg_run': 'AVG(run_time)',
            'avg_finish': 'AVG(finish_time)'
        }
        computed_race_data_list = []
        for gender in gender_list:
            for age_group in age_group_list:
                results = self.raceresult_set.filter(
                    age_group=age_group,
                    sex=gender,
                    race_status='Finished').extra(
                    select=select_query).values('avg_swim', 'avg_bike', 'avg_run', 'avg_finish')[0]
                for key, value in results.items():
                    # We don't want to cast `None` as a string, but we want to cast the
                    # `datetime.timedelta` value as a string for saving into the db.
                    if value is not None:
                        results[key] = timedelta(microseconds=value)
                race_data = ComputedRaceData(race=self,
                                             sex=gender,
                                             age_group=age_group,
                                             average_swim_time=results['avg_swim'],
                                             average_bike_time=results['avg_bike'],
                                             average_run_time=results['avg_run'],
                                             average_finish_time=results['avg_finish'])
                computed_race_data_list.append(race_data)
        return computed_race_data_list

    def __str__(self):
            return '{0} {1}'.format(self.title, self.date.year)

    class Meta:
        unique_together = ('distance', 'title', 'date',)


class RaceResult(models.Model):
    AGE_GROUPS = Choices('Pro', '18-24', '25-29', '30-34', '35-39',
                         '40-44', '45-49', '50-54', '55-59', '60-64',
                         '65-69', '70-74', '75-79', '80-999')
    SEXES = Choices('M', 'F')
    RACE_STATUSES = Choices('DQ', 'DNS', 'DNF', 'Finished')
    race = models.ForeignKey(Race, on_delete=models.CASCADE)
    athlete_name = models.CharField(max_length=255)
    age_group = models.CharField(max_length=255, choices=AGE_GROUPS)
    sex = models.CharField(max_length=1, choices=SEXES)
    athlete_country = models.CharField(max_length=255, blank=True, null=True)
    division_rank = models.IntegerField(blank=True, null=True,)
    gender_rank = models.IntegerField(blank=True, null=True,)
    overall_rank = models.IntegerField(blank=True, null=True,)
    swim_time = models.DurationField(blank=True, null=True,)
    bike_time = models.DurationField(blank=True, null=True,)
    run_time = models.DurationField(blank=True, null=True,)
    finish_time = models.DurationField(blank=True, null=True,)
    points = models.IntegerField(blank=True, null=True,)
    race_status = models.CharField(choices=RACE_STATUSES,
                                   default=RACE_STATUSES['Finished'], max_length=40)

    def finish_time_as_string(self):
        return self.finish_time.strftime('%H:%M:%S') if self.finish_time else '---'
    finish_time_as_string.short_description = "finish time"

    str_finish_time = property(finish_time_as_string)

    def __str__(self):
            return '{0} - {1}'.format(self.athlete_name, self.finish_time)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['race_id', 'athlete_name', 'finish_time', 'age_group', 'overall_rank'],
                name="unique_result"),
        ]

class ComputedRaceData(models.Model):
    race = models.ForeignKey('Race', on_delete=models.CASCADE)
    age_group = models.CharField(max_length=255, choices=RaceResult.AGE_GROUPS)
    sex = models.CharField(max_length=1, choices=RaceResult.SEXES)
    average_swim_time = models.DurationField(blank=True, null=True,)
    average_bike_time = models.DurationField(blank=True, null=True,)
    average_run_time = models.DurationField(blank=True, null=True,)
    average_finish_time = models.DurationField(blank=True, null=True,)

ironman/forms.py
from django import forms
from .models import Race, RaceResult
from django.forms import ModelChoiceField

class RaceModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return str(obj.date.year)

class RaceFilterForm(forms.Form):
	race_id = RaceModelChoiceField(
		queryset=Race.objects.none(),
		widget=forms.Select(attrs={"onChange": 'submit()', 'class': 'form-control'}),
		label='',
		empty_label=None)

	age_group = forms.ChoiceField(
		choices=[(None, 'All')] + RaceResult.AGE_GROUPS,
		widget=forms.Select(attrs={'onchange': 'submit();', 'class': 'form-control'}),
		label='')
	sex = forms.ChoiceField(
		choices=[(None, 'Both')] + RaceResult.SEXES,
		widget=forms.Select(attrs={'onchange': 'submit();', 'class': 'form-control'}),
		label='')

	def __init__(self, race, *args, **kwargs):
		super(RaceFilterForm, self).__init__(*args, **kwargs)
		self.fields['race_id'].queryset = Race.objects.filter(title=race.title)

ironman/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Race, RaceResult
from .forms import RaceFilterForm
from django.db.models import Q, Count, F
from django.views import generic
from django.utils.http import urlencode
from django.urls import reverse
from .constants import WEBDRIVER_VERSION


class IndexView(generic.TemplateView):
	template_name = 'races/index.html'
	
	def get_context_data(self, *args, **kwargs):
		context = super(IndexView, self).get_context_data(**kwargs)
		q = self.request.GET.get('q')
		search_type = self.request.GET.get('search_type', 'race')
		if search_type == 'race':
			races = Race.objects \
				.filter(Q(title__contains=q) if q else Q()) \
				.order_by('-date')
			context['races'] = races
		else:
			if self.request.GET.get('exact'):
				filter = Q(athlete_name=q)
			else:
				filter = Q(athlete_name__contains=q) if q else Q() 
			race_results = RaceResult.objects \
				.filter(filter) \
				.order_by('-race__date') \
				[:50]
			context['race_results'] = race_results
		context['q'] = q
		context['search_type'] = search_type
		return context

class RaceView(generic.TemplateView):
	template_name = 'races/results.html'

	def dispatch(self, request, *args, **kwargs):
		race_id = request.GET.get('race_id')
		race = get_object_or_404(Race, pk=kwargs['race_id'])
		if race_id and str(race.id) != str(race_id):
			path = reverse('ironman:race', kwargs={'race_id': race_id})
			helper_query_dict = request.GET.copy()
			helper_query_dict.pop('race_id')
			params = helper_query_dict.urlencode()
			return redirect("%s?%s" % (path, params));
		return super(RaceView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(**kwargs)
		race_id = kwargs['race_id']
		age_group = self.request.GET.get('age_group')
		sex = self.request.GET.get('sex')		
		sort = self.request.GET.get('sort', 'finish_time')
		order = self.request.GET.get('order', 'asc')
		race = get_object_or_404(Race, pk=race_id)
		filter_obj = Q(race_id=race.id) & Q(finish_time__isnull=False)
		if age_group:
			filter_obj &= Q(age_group=age_group)
		if sex:
			filter_obj &= Q(sex=sex)
		race_results = RaceResult \
			.objects \
			.filter(filter_obj)
		if order == 'asc':
			race_results = race_results.order_by(F(sort).asc(nulls_last=True))
		else:
			race_results = race_results.order_by(F(sort).desc(nulls_last=True))
		races_all_years = Race.objects.filter(title=race.title)
		context['race_results'] = race_results
		context['race'] = race
		context['race_filter_form'] = RaceFilterForm(race, initial={'age_group': age_group, 'sex': sex, 'race_id': race.pk})
		return context

class StatsView(generic.TemplateView):
	template_name = 'races/stats.html'

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(**kwargs)
		context['search_type'] = 'stats'
		context['race_counts'] = Race.objects.all().values('distance').annotate(total=Count('distance'))
		context['participant_counts'] = RaceResult.objects.all().values('race__distance').annotate(total=Count('race__distance'))
		context['race_by_version'] = Race.objects.all().values('version').annotate(total=Count('version'))
		context['bad_races'] = Race.objects.exclude(version=WEBDRIVER_VERSION)
		return context

ironman/templates/races/athlete.html
<div>
	<a href="{% url 'ironman:index' %}?search_type=athlete&q={{ race_result.athlete_name }}&exact=1">
		{{ race_result.athlete_name }}
	</a>
	<br />
	<span>	
		{{ race_result.sex }}
		{{ race_result.age_group }}
	</span>
</div>

ironman/templates/races/athletes.html
<table class="table">
	<thead>
		<th>Athlete</th>
		<th>Div.</th>
		<th>Gen.</th>
		<th>Ovr.</th>
		<th>Swim</th>
		<th>Bike</th>
		<th>Run</th>
		<th>Time</th>
		<th>Race</th>
	</thead>
	{% for race_result in race_results %}
	<tr>
		<td>
			{% include "races/athlete.html" with race_result=race_result %}
		</td>
		<td>{{ race_result.division_rank }}</td>
		<td>{{ race_result.gender_rank }}</td>
		<td>{{ race_result.overall_rank }}</td>
		<td>{{ race_result.swim_time }}</td>
		<td>{{ race_result.bike_time }}</td>
		<td>{{ race_result.run_time }}</td>
		<td>{{ race_result.finish_time }}</td>
		<td>
			{% include "races/race.html" with race=race_result.race only %}
		</td>
	</tr>
	{% endfor %}
</table>

ironman/templates/races/base_generic.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'races/dashboard.css' %}">
    <link rel="stylesheet" href="{% static "fontawesome/css/fontawesome-all.min.css" %}">

    <title>List of Ironman Results</title>
  </head>
  <body>
    {% include "races/header.html" %}

    <div class="container-fluid">
      <div class="row">
        {% include "races/left_nav.html" %}
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          {% block content %}
          {% endblock %}
        </main>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

ironman/templates/races/header.html
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
	<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Ironman Results</a>
	<form
		action="{% url 'ironman:index' %}" method="get" class="w-100">
		<input
			class="form-control form-control-dark" 
			type="text"
			placeholder="Search"
			aria-label="Search"
			name="q"
			value="{% firstof q '' %}">
		<input name="search_type" value="{{ search_type }}" type="hidden">
	</form>
</nav>

ironman/templates/races/index.html
{% extends 'races/base_generic.html' %}

{% block content %}

{% if races %}
	{% include "races/races.html" with races=races only %}
{% endif %}

{% if race_results %}
	{% include "races/athletes.html" with race_results=race_results only %}
{% endif %}
{% endblock %}

ironman/templates/races/left_nav.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
	<div class="sidebar-sticky">
		<ul class="nav flex-column">
			<li class="nav-item">
				<a class="nav-link {% if search_type == 'race' %}active{% endif %}" href="{% url 'ironman:index' %}?search_type=race">
					Races
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link {% if search_type == 'athlete' %}active{% endif %}" href="{% url 'ironman:index' %}?search_type=athlete">
					Athletes
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link {% if search_type == 'stats' %}active{% endif %}" href="{% url 'ironman:stats' %}?search_type=stats">
					Stats
				</a>
			</li>
		</ul>
	</div>
</nav>

ironman/templates/races/race.html
<a href="{% url 'ironman:race' race.id %}">
	{{ race.title }}
	{{ race.date }}
</a>

ironman/templates/races/races.html
<ul>
{% for race in races %}
	<li>
		{% include "races/race.html" with race=race only %}
	</li>
{% endfor %}
</ul>

ironman/templates/races/results.html
{% extends 'races/base_generic.html' %}
{% load sortable_column %}

{% block content %}
<h1>{% include "races/race.html" with race=race %}</h1>

<form class="pb-3" method="GET" action="{% url 'ironman:race' race.id%}">
	<div class="form-row">
		{% for field in race_filter_form.visible_fields %}
			<div class="col">
				{{ field }}
			</div>
		{% endfor %}
	</div>
</form>

<table class="table table-hover">
	<thead>
		<th>#</th>
		{% sortable_column request=request property="athlete_name" title="Name" %}
		{% sortable_column request=request property="division_rank" title="Div." %}
		{% sortable_column request=request property="gender_rank" title="Gen." %}
		{% sortable_column request=request property="overall_rank" title="Ovr." %}
		{% sortable_column request=request property="swim_time" title="Swim" %}
		{% sortable_column request=request property="bike_time" title="Bike" %}
		{% sortable_column request=request property="run_time" title="Run" %}
		{% sortable_column request=request property="finish_time" title="Time" %}
	</thead>
{% for race_result in race_results %}
	<tr>
		<td>{{ forloop.counter }}</td>
		<td>
			{% include "races/athlete.html" with race_result=race_result%}
		</td>
		<td>{{ race_result.division_rank }}</td>
		<td>{{ race_result.gender_rank }}</td>
		<td>{{ race_result.overall_rank }}</td>
		<td>{{ race_result.swim_time }}</td>
		<td>{{ race_result.bike_time }}</td>
		<td>{{ race_result.run_time }}</td>
		<td>{{ race_result.finish_time }}</td>
	</tr>
{% endfor %}
</table>
{% endblock %}

ironman/templates/races/stats.html
{% extends 'races/base_generic.html' %}

{% block content %}

<div class="container mt-3">
	<dl>
		<dt>Number of races:</dt>
		<dd>{{ race_counts }}</dd>
		<dt>Number of participants:</dt>
		<dd>{{ participant_counts }}</dd>
		<dt>Race by version count</dt>
		<dd>{{ race_by_version }}</dd>
		<dt>Races without results</dt>
		<dd>{{ bad_races }}</dd>
	</dl>
</div>

{% endblock %}